package com.recruitease.ticket_service;

import org.modelmapper.ModelMapper;
import org.modelmapper.record.RecordModule;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.context.annotation.Bean;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;
import org.springframework.jdbc.core.JdbcTemplate;

@SpringBootApplication
@EnableDiscoveryClient
@EnableJpaAuditing
public class TicketServiceApplication {

	public static void main(String[] args) {
		SpringApplication.run(TicketServiceApplication.class, args);
	}

	@Bean
	public ModelMapper modelMapper() {
		return new ModelMapper().registerModule(new RecordModule());
	}

//	@Bean
//	public CommandLineRunner createTableRunner(JdbcTemplate jdbcTemplate) {
//		return args -> {
//			String createTableSQL = """
//                CREATE TABLE IF NOT EXISTS ticket (
//					ticket_id varchar(255) generated by default as identity,
//					created_at timestamp(6),
//					creator_id varchar(255),
//					creator_role smallint check (creator_role between 0 and 1),
//					description varchar(255),
//					modified_at timestamp(6),
//					note varchar(255),
//					status smallint check (status between 0 and 2),
//					subject varchar(255),
//					type smallint check (type between 0 and 6),
//					primary key (ticket_id)
//				);
//            """;
//
//			jdbcTemplate.execute(createTableSQL);
//			System.out.println("Ticket table created or already exists.");
//		};
//	}
}
